
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="cyber-section">
      <div className="container px-4 mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            <span className="neon-text">Legal Disclaimer</span>
          </h2>
          <p className="text-gray-300 max-w-2xl mx-auto">
            Important information about the use of Roleplay Companion GPT.
          </p>
        </div>
        
        <div className="cyber-panel max-w-4xl mx-auto">
          <div className="space-y-6 text-gray-300">
            <p>
              <strong className="text-white">Adult Content Warning:</strong> Roleplay Companion GPT is intended for users 18 years of age and older. The service may contain explicit adult content and themes unsuitable for minors. By accessing this service, you confirm that you are at least 18 years old and agree to encounter potentially explicit material.
            </p>
            
            <p>
              <strong className="text-white">Entertainment Purposes Only:</strong> Roleplay Companion GPT is provided strictly for entertainment and creative purposes. Any advice, information, or content generated by the AI should not be considered professional guidance. Users should not rely on the AI for medical, legal, financial, or other professional advice.
            </p>
            
            <p>
              <strong className="text-white">Fictional Content:</strong> All characters, scenarios, and conversations generated by Roleplay Companion GPT are entirely fictional. Any resemblance to real persons, living or dead, or actual events is purely coincidental. The AI does not represent real individuals nor should its portrayal of historical figures be considered historically accurate.
            </p>
            
            <p>
              <strong className="text-white">User Responsibility:</strong> Users are solely responsible for their interactions with Roleplay Companion GPT. AI Web Tools LLC and OpenAI do not endorse or encourage illegal, harmful, or unethical activities. Users agree not to use the service to:
            </p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>Engage in or promote illegal activities</li>
              <li>Create content that violates the rights of others</li>
              <li>Generate content that promotes harm to individuals or groups</li>
              <li>Create or distribute non-consensual intimate imagery</li>
              <li>Use the service for harassment or bullying</li>
            </ul>
            
            <p>
              <strong className="text-white">Limitation of Liability:</strong> To the maximum extent permitted by applicable law, AI Web Tools LLC and OpenAI disclaim all warranties and liabilities related to the use of Roleplay Companion GPT. Neither entity shall be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting from your use of the service.
            </p>
            
            <p>
              <strong className="text-white">Privacy:</strong> Your interactions with Roleplay Companion GPT may be recorded and analyzed to improve the service. For more information on how your data is used, please refer to the <a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-cyber-neon-blue hover:underline">Privacy Policy</a>.
            </p>
            
            <p>
              <strong className="text-white">Terms of Service:</strong> Use of Roleplay Companion GPT is subject to the <a href="https://aiwebtools.lovable.app/?via=aiwebtools" target="_blank" rel="noopener noreferrer" className="text-cyber-neon-blue hover:underline">Terms of Service</a>.
            </p>
            
            <p>
              <strong className="text-white">Changes to Service:</strong> AI Web Tools LLC and OpenAI reserve the right to modify, suspend, or discontinue Roleplay Companion GPT at any time without notice.
            </p>
            
            <p>
              By using Roleplay Companion GPT, you acknowledge that you have read, understood, and agree to this disclaimer.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
